package com.rakshan.codereview.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for returning review quality prediction results.
 * Contains the predicted quality score, trend direction, and confidence metric
 * generated by the ML forecasting feature using Apache Commons Math SimpleRegression.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ForecastDto {

    /** Predicted quality score for the submission (0.0 - 5.0 scale) */
    private Double predictedScore;

    /** Trend direction: "IMPROVING", "DECLINING", or "STABLE" */
    private String trendDirection;

    /** Confidence score of the prediction (0.0 - 1.0, where 1.0 is highest confidence) */
    private Double confidence;

    /** Number of historical data points used for the prediction */
    private Integer dataPointsUsed;

    /** Brief explanation of the prediction factors */
    private String explanation;
}
